### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by Syeon0305** [yutong-xia/CaST#1]
how to get dataset(/pems8/dataset.npy, peacor_adj.npy ....)?

**Comment by Sonder-arch** [comment]
I have the same question and look forward to the author's reply.

**Comment by 6586744** [comment]
need help too.

**Comment by yutong-xia** [comment]
Thank you for your interest in our work. To generate the 'peacor_adj.npy' file, you can use the code provided below. 

```
def get_peacor_adj(data_path, threshold, save=False):
    # Load the dataset
    data = np.load(data_path + 'train.npz')['data']
    print("Data shape:", data.shape)
    
    # Compute the Pearson correlation coefficient matrix
    peacor = torch.corrcoef(torch.Tensor(data[...,0]).permute(1, 0))
    
    # Apply threshold
    peacor[peacor < threshold] = 0
    peacor[torch.eye(peacor.shape[0], dtype=bool)] = 0

    # Normalize the coefficients
    nonzero_peacor = peacor[peacor != 0]
    p_min, p_max = nonzero_peacor.min(), nonzero_peacor.max()
    peacor[peacor != 0] = (nonzero_peacor - p_min) / (p_max - p_min)

    # Visualization
    plt.figure(dpi=100)
    sns.heatmap(peacor)
    plt.show()
    
    # Save the result
    if save:
        np.save(data_path + 'peacor_adj.npy', peacor)
```

For customization, you can also consider implementing your own method for creating the edge attribute, which can be an alternative to the Pearson correlation or the Time-delayed Dynamic Time Warping (DTW) method used in our paper.

**Comment by hczs** [comment]
> Thank you for your interest in our work. To generate the 'peacor_adj.npy' file, you can use the code provided below.
> 
> ```
> def get_peacor_adj(data_path, threshold, save=False):
>     # Load the dataset
>     data = np.load(data_path + 'train.npz')['data']
>     print("Data shape:", data.shape)
>     
>     # Compute the Pearson correlation coefficient matrix
>     peacor = torch.corrcoef(torch.Tensor(data[...,0]).permute(1, 0))
>     
>     # Apply threshold
>     peacor[peacor < threshold] = 0
>     peacor[torch.eye(peacor.shape[0], dtype=bool)] = 0
> 
>     # Normalize the coefficients
>     nonzero_peacor = peacor[peacor != 0]
>     p_min, p_max = nonzero_peacor.min(), nonzero_peacor.max()
>     peacor[peacor != 0] = (nonzero_peacor - p_min) / (p_max - p_min)
> 
>     # Visualization
>     plt.figure(dpi=100)
>     sns.heatmap(peacor)
>     plt.show()
>     
>     # Save the result
>     if save:
>         np.save(data_path + 'peacor_adj.npy', peacor)
> ```
> 
> For customization, you can also consider implementing your own method for creating the edge attribute, which can be an alternative to the Pearson correlation or the Time-delayed Dynamic Time Warping (DTW) method used in our paper.

Thank you very much for your work, but I have the same problem with this issue, that is, there are some other files, how do I get these files, or is there a python script that can generate these files?
Issue Address: https://github.com/yutong-xia/CaST/issues/2
Need files: such as "adj_mx_pems08.pkl", "time_dalay_attr.pkl", "sparse_adj.npy", "peacor_adj.npy" and "dist_adj.npy".

**Comment by Dx3281101** [comment]
> 如何获取数据集（/pems8/dataset.npy，peacor_adj.npy ....）？

Excuse me for the interruption.
Have you successfully run this model? I want to run it, but I'm missing some necessary data files . Could you please share how you handled this issue?
I would greatly appreciate it.
