### ISSUE TITLE
How to get dataset?

### ISSUE THREAD

**Issue by RuiAN77** [yutong-xia/CaST#2]
Hello,
Thank you for this project and contribution.
When I try to run the code, I encounter problems with missing datasets such as "adj_mx_pems08.pkl", "time_dalay_attr.pkl", "sparse_adj.npy", "peacor_adj.npy" and "dist_adj.npy". how do I get these dataset?
Thanks!

**Comment by Dx3281101** [comment]
> Hello, Thank you for this project and contribution. When I try to run the code, I encounter problems with missing datasets such as "adj_mx_pems08.pkl", "time_dalay_attr.pkl", "sparse_adj.npy", "peacor_adj.npy" and "dist_adj.npy". how do I get these dataset? Thanks!

Did you solve this problem? I would be grateful if you could share the data file.

**Comment by yutong-xia** [comment]
Thanks for your interest in our work. These are used to generate edge attributes. You can design your own attribute or generate these files based on the code I provide at https://github.com/yutong-xia/CaST/issues/1#issuecomment-2016405187. For more details about how we built the edge attributes refer to Appendix D of our paper. Thanks!
