### ISSUE TITLE
Number of edges

### ISSUE THREAD

**Issue by suzy0223** [yutong-xia/CaST#3]
Thanks for sharing the code. 

I find the code predefined the number of edges for each dataset. Because the predefined number of edges cannot match the number of links in the adjacent matrix file, I'd like to know if the number includes self-loop. Does the code use the "Gaussian distance" to filter some links in the adjacent matrix file? 

Much appreciated : )

**Comment by hczs** [comment]
Excuse me for the interruption.
Have you successfully run this model? I want to run it, but I'm missing some necessary data files (reference: https://github.com/yutong-xia/CaST/issues/2). Could you please share how you handled this issue?
I would greatly appreciate it.

**Comment by Dx3281101** [comment]
> 抱歉打扰了。 我想运行这个模型，但我缺少一些必要的数据文件（参考：#2）。您能分享一下您解决的问题吗？ 我将不胜感激。

请问您解决这个问题了吗？能分享一下数据文件吗，我将不胜感激

**Comment by hczs** [comment]
> > 抱歉打扰了。 我想运行这个模型，但我缺少一些必要的数据文件（参考：#2）。您能分享一下您解决的问题吗？ 我将不胜感激。
> 
> 请问您解决这个问题了吗？能分享一下数据文件吗，我将不胜感激

并没有解决

**Comment by yutong-xia** [comment]
Thanks for your interest in our work. In this project, the existence of edges is defined not only by distance but also by matrics like person correlations and DTW. For a detailed discussion, please refer to Appendix D of our paper. Thanks!
