### ISSUE TITLE
All dependent versions of the program

### ISSUE THREAD

**Issue by hczs** [yutong-xia/CaST#4]
Hello, can you provide a copy of the program's dependent version requirements.txt file to the repository?  It is very difficult to find a working version dependency, such as torch and torch-scatter version correspondence is very complex, let alone PyG version

**Comment by yutong-xia** [comment]
Thanks for your interest in our work. The versions of the dependencies used in this project are now accessible in [`requirements.txt`](https://github.com/yutong-xia/CaST/blob/main/requirements.txt).

**Comment by yanyana117** [comment]
> requirements.txt

Same here. I found it's difficult to disappear the conflict between torch-scatter, torch-sparse, and pytorch. I'm wondering if you solve this issue. Thanks.
