### ISSUE TITLE
how to get dataset?

### ISSUE THREAD

**Issue by Jianghaiyang0729** [yutong-xia/CaST#5]
How can I get these three files: dist_adj.npy, peacor_adj.npy, sparse_adj.npy? And also dataset.npy described in the dataset part? When I click on the link of PEMS-08, I can only get the files: distance.csv and pems08.npz.
I guess these four files are not raw data, but the authors generated. CaST is a very impressive work, and I plan to use it as a baseline model in my research. I hope to get your reply!

**Comment by yutong-xia** [comment]
Thanks for you interest in our work. We have provide `peacor_adj.npy`, `sparse_adj.npy`, and `dist_adj.npy` in the `.\data\PEMS08\` directory for reference.

**Comment by yutong-xia** [comment]
For `dataset.npy`, you can generate use the following code

```
data = np.load('./data/PEMS08/pems08.npz')['data']
np.save('./data/PEMS08/dataset.npy', data)
```
