### ISSUE TITLE
No module named' src '

### ISSUE THREAD

**Issue by coderfhw** [yutong-xia/CaST#7]
Dear yutong，
       I want to know why the error 'ModulaNotFoundError: No module named' src 'is displayed when I am running main.py.

**Comment by suzy0223** [comment]
Hi, have you solved this issue? I meet the same issue. I try to add the path into environment but failed. Thx

**Comment by yutong-xia** [comment]
Hi, you may need to set the working directory using `export PYTHONPATH="${PYTHONPATH}:/path/to/your/project/"` or `export PYTHONPATH="/path/to/your/project/"`.
